server:
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: ACV-CA
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    ACV-UA: /ACV-UA/**
      #面向服务路由
    #customSensitiveHeaders: true
    #sensitiveHeaders:

    #path:
    #serviceId:
    ACV-VA: /ACV-VA/**
    atcc-serviceplatform-messageadapter: /atcc-serviceplatform-messageadapter/**
    atcc-serviceplartform-b2badapter: /atcc-serviceplartform-b2badapter/**

  api-a-url:
    path: /api-a-url
    url: http://localhost:8080/
  AccessFilter:
    pre:
      disable: false

  #retryable: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutIntMilliseconds: 120000

jwt:
  SECRET_BAIDU: qweRTYuioasdFGHjklzxcVBNmradio
  SECRET_HU: qweRTYuioasdFGHjklzxcVBNmhu
  SECRET_AUTO: qweRTYuioasdFGHjklzxcVBNmauto
  SECRET_JD: qweRTYuioasdFGHjklzxcVBNmjd
  CODE_EXPIREIN: 300
  REFRESH_TOKEN_EXPIREIN: 2592000
  ACCESS_TOKEN_EXPIREIN: 7200
  AUTHORITY_LIST: scp01001 scp01002 scp01003 scp02001 read

