server:
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: ACV-CA

zuul:
  routes:
    users:
      path: /ACV-UA/**
      serviceId: ACV-UA

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000